# Generated by Django 5.0.3 on 2024-03-25 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokobuku', '0004_review_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rate',
            field=models.IntegerField(default=1),
        ),
    ]
